#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("Plugin.Android.Fused.Resource", IsApplication=false)]

namespace Plugin.Android.Fused
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010003
			public static int buttonSize = 2130771971;
			
			// aapt resource value: 0x7f010002
			public static int circleCrop = 2130771970;
			
			// aapt resource value: 0x7f010004
			public static int colorScheme = 2130771972;
			
			// aapt resource value: 0x7f010001
			public static int imageAspectRatio = 2130771969;
			
			// aapt resource value: 0x7f010000
			public static int imageAspectRatioAdjust = 2130771968;
			
			// aapt resource value: 0x7f010005
			public static int scopeUris = 2130771973;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050008
			public static int common_google_signin_btn_text_dark = 2131034120;
			
			// aapt resource value: 0x7f050000
			public static int common_google_signin_btn_text_dark_default = 2131034112;
			
			// aapt resource value: 0x7f050001
			public static int common_google_signin_btn_text_dark_disabled = 2131034113;
			
			// aapt resource value: 0x7f050002
			public static int common_google_signin_btn_text_dark_focused = 2131034114;
			
			// aapt resource value: 0x7f050003
			public static int common_google_signin_btn_text_dark_pressed = 2131034115;
			
			// aapt resource value: 0x7f050009
			public static int common_google_signin_btn_text_light = 2131034121;
			
			// aapt resource value: 0x7f050004
			public static int common_google_signin_btn_text_light_default = 2131034116;
			
			// aapt resource value: 0x7f050005
			public static int common_google_signin_btn_text_light_disabled = 2131034117;
			
			// aapt resource value: 0x7f050006
			public static int common_google_signin_btn_text_light_focused = 2131034118;
			
			// aapt resource value: 0x7f050007
			public static int common_google_signin_btn_text_light_pressed = 2131034119;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public static int common_full_open_on_phone = 2130837504;
			
			// aapt resource value: 0x7f020001
			public static int common_google_signin_btn_icon_dark = 2130837505;
			
			// aapt resource value: 0x7f020002
			public static int common_google_signin_btn_icon_dark_disabled = 2130837506;
			
			// aapt resource value: 0x7f020003
			public static int common_google_signin_btn_icon_dark_focused = 2130837507;
			
			// aapt resource value: 0x7f020004
			public static int common_google_signin_btn_icon_dark_normal = 2130837508;
			
			// aapt resource value: 0x7f020005
			public static int common_google_signin_btn_icon_dark_pressed = 2130837509;
			
			// aapt resource value: 0x7f020006
			public static int common_google_signin_btn_icon_light = 2130837510;
			
			// aapt resource value: 0x7f020007
			public static int common_google_signin_btn_icon_light_disabled = 2130837511;
			
			// aapt resource value: 0x7f020008
			public static int common_google_signin_btn_icon_light_focused = 2130837512;
			
			// aapt resource value: 0x7f020009
			public static int common_google_signin_btn_icon_light_normal = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public static int common_google_signin_btn_icon_light_pressed = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public static int common_google_signin_btn_text_dark = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public static int common_google_signin_btn_text_dark_disabled = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public static int common_google_signin_btn_text_dark_focused = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public static int common_google_signin_btn_text_dark_normal = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public static int common_google_signin_btn_text_dark_pressed = 2130837519;
			
			// aapt resource value: 0x7f020010
			public static int common_google_signin_btn_text_light = 2130837520;
			
			// aapt resource value: 0x7f020011
			public static int common_google_signin_btn_text_light_disabled = 2130837521;
			
			// aapt resource value: 0x7f020012
			public static int common_google_signin_btn_text_light_focused = 2130837522;
			
			// aapt resource value: 0x7f020013
			public static int common_google_signin_btn_text_light_normal = 2130837523;
			
			// aapt resource value: 0x7f020014
			public static int common_google_signin_btn_text_light_pressed = 2130837524;
			
			// aapt resource value: 0x7f020015
			public static int common_ic_googleplayservices = 2130837525;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060000
			public static int adjust_height = 2131099648;
			
			// aapt resource value: 0x7f060001
			public static int adjust_width = 2131099649;
			
			// aapt resource value: 0x7f060006
			public static int auto = 2131099654;
			
			// aapt resource value: 0x7f060007
			public static int dark = 2131099655;
			
			// aapt resource value: 0x7f060003
			public static int icon_only = 2131099651;
			
			// aapt resource value: 0x7f060008
			public static int light = 2131099656;
			
			// aapt resource value: 0x7f060002
			public static int none = 2131099650;
			
			// aapt resource value: 0x7f060004
			public static int standard = 2131099652;
			
			// aapt resource value: 0x7f060005
			public static int wide = 2131099653;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f030000
			public static int google_play_services_version = 2130903040;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public static int common_google_play_services_enable_button = 2130968577;
			
			// aapt resource value: 0x7f040002
			public static int common_google_play_services_enable_text = 2130968578;
			
			// aapt resource value: 0x7f040003
			public static int common_google_play_services_enable_title = 2130968579;
			
			// aapt resource value: 0x7f040004
			public static int common_google_play_services_install_button = 2130968580;
			
			// aapt resource value: 0x7f040005
			public static int common_google_play_services_install_text_phone = 2130968581;
			
			// aapt resource value: 0x7f040006
			public static int common_google_play_services_install_text_tablet = 2130968582;
			
			// aapt resource value: 0x7f040007
			public static int common_google_play_services_install_title = 2130968583;
			
			// aapt resource value: 0x7f040008
			public static int common_google_play_services_notification_ticker = 2130968584;
			
			// aapt resource value: 0x7f040000
			public static int common_google_play_services_unknown_issue = 2130968576;
			
			// aapt resource value: 0x7f040009
			public static int common_google_play_services_unsupported_text = 2130968585;
			
			// aapt resource value: 0x7f04000a
			public static int common_google_play_services_unsupported_title = 2130968586;
			
			// aapt resource value: 0x7f04000b
			public static int common_google_play_services_update_button = 2130968587;
			
			// aapt resource value: 0x7f04000c
			public static int common_google_play_services_update_text = 2130968588;
			
			// aapt resource value: 0x7f04000d
			public static int common_google_play_services_update_title = 2130968589;
			
			// aapt resource value: 0x7f04000e
			public static int common_google_play_services_updating_text = 2130968590;
			
			// aapt resource value: 0x7f04000f
			public static int common_google_play_services_updating_title = 2130968591;
			
			// aapt resource value: 0x7f040010
			public static int common_google_play_services_wear_update_text = 2130968592;
			
			// aapt resource value: 0x7f040011
			public static int common_open_on_phone = 2130968593;
			
			// aapt resource value: 0x7f040012
			public static int common_signin_button_text = 2130968594;
			
			// aapt resource value: 0x7f040013
			public static int common_signin_button_text_long = 2130968595;
			
			// aapt resource value: 0x7f040014
			public static int library_name = 2130968596;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] LoadingImageView = new int[]
			{
					2130771968,
					2130771969,
					2130771970};
			
			// aapt resource value: 2
			public static int LoadingImageView_circleCrop = 2;
			
			// aapt resource value: 1
			public static int LoadingImageView_imageAspectRatio = 1;
			
			// aapt resource value: 0
			public static int LoadingImageView_imageAspectRatioAdjust = 0;
			
			public static int[] SignInButton = new int[]
			{
					2130771971,
					2130771972,
					2130771973};
			
			// aapt resource value: 0
			public static int SignInButton_buttonSize = 0;
			
			// aapt resource value: 1
			public static int SignInButton_colorScheme = 1;
			
			// aapt resource value: 2
			public static int SignInButton_scopeUris = 2;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
